### ISSUE TITLE
running on Cray cluster (XC30)

### ISSUE THREAD

**Issue by HongjianFang** [rmodrak/seisflows#33]
Hi Ryan, 
I am using seisflows for some tests. Thanks a lot for
 sharing this amazing package, it really makes my life easier. But I have
 trouble to run it on a 'aprun' based Cray cluster (also SLURM batch system), it seems some environment variables are missing. For example:
in system/slurm_sm.py
 def getnode(self):

 """ Gets number of running task
 """
 gid = os.getenv('SLURM_GTIDS').split(',')
 lid = int(os.getenv('SLURM_LOCALID'))
 return int(gid[lid])

The following changes also do now work:
1, based on your recommendation:
 def getnode(self):

 """ Gets number of running task
 """
       from mpi4py import MPI
       return MPI.COMM_WORLD.Get_rank()
2, found online:
        def getnode(self):
        """ Gets number of running task
        """
           return int(os.getenv('ALPS_APP_PE'))

The errors seem 'io' related (two process are trying to make the same directory?).
more comments or advices are appreciated.

Thanks in advance,
Fang

**Comment by rmodrak** [comment]
```
The errors seem 'io' related (two process are trying to make the same directory?).
more comments or advices are appreciated.
```

Hi Fang, Good question.  I think this might be something we could help with.  By chance, do you have a traceback that you post?  In other words, what error message is returned on failure?

**Comment by HongjianFang** [comment]
Hi Ryan,
The error messages are attached.
Thanks a lot.

Best 
Fang

[ALPS_APP_PE_Error.txt](https://github.com/PrincetonUniversity/seisflows/files/182263/ALPS_APP_PE_Error.txt)
[MPI_Get_rankError.txt](https://github.com/PrincetonUniversity/seisflows/files/182264/MPI_Get_rankError.txt)

**Comment by rmodrak** [comment]
For troubleshooting, could you try rerunning it with NTASK=1 and post the traceback?  Thanks, Ryan

**Comment by HongjianFang** [comment]
I remember it could run successfully if NTASK<=16 (it seems each compute node has 16 cores). I'll check with NTASK=1 in a minute.
Cheers,
Fang

**Comment by HongjianFang** [comment]
Sorry I was wrong, the error message with NTASK=1 is as followed:
Application 7572365 resources: utime ~1s, stime ~2s, Rss ~49308, inblocks ~68489, outblocks ~66336
Application 7572367 resources: utime ~20s, stime ~1s, Rss ~74528, inblocks ~33615, outblocks ~193005
Application 7572368 resources: utime ~45s, stime ~1s, Rss ~270884, inblocks ~124629, outblocks ~8589
Application 7572369 resources: utime ~0s, stime ~1s, Rss ~45236, inblocks ~17330, outblocks ~313
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/7572370/run_head", line 28, in <module>
    func(**kwargs)
  File "/users/hfang/packages/seisflows/seisflows/solver/specfem2d.py", line 164, in smooth
    self.save(path, kernels, suffix='_kernel')
  File "/users/hfang/packages/seisflows/seisflows/solver/base.py", line 273, in save
    savebin(model[key][iproc], path, iproc, prefix+key+suffix)
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 41, in savebin
    write_fortran(v, join(path, filename))
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 91, in write_fortran
    with open(filename, 'wb') as file:
IOError: [Errno 2] No such file or directory: u'/users/hfang/packages/tests/checkers/scratch/evalgrad/kernels/sum/proc000000_vs_kernel.bin'
Application 7572370 exit codes: 1
Application 7572370 resources: utime ~2s, stime ~1s, Rss ~125544, inblocks ~18983, outblocks ~2
Copying data...
Starting iteration 1
Generating synthetics
Computing gradient
...

**Comment by rmodrak** [comment]
Hi Fang,

As we were talking about earlier by email, I think some minor modifications to system.mpi would allow you to run inversions on your cluster.

You mentioned your cluster has aprun  instead of mpiexec.  The main fix I think would be to replace every instance of ``mpiexec -n``  in seisflows/system/mpi.py with ``aprun -n``, and then specify ``SYSTEM='slurm_sm'`` and ``MPIARGS=''``in your parameters file.  If you try this, you might get some "fork" warnings that are safe to disregard.

Once we get it to run, we could think about some generalizations that would make it easier for other Cray users.

Ryan

**Comment by rmodrak** [comment]
P.S.  On our cluster, we have mpiexec and srun but not aprun.  I just verified that in our environment, it works to replace ``mpiexec -n`` with ``srun -n``.  This gives me hope that in your environment, it might work to replace ``mpiexec -n`` with ``aprun -n``.

**Comment by HongjianFang** [comment]
Hi Ryan,
   Thanks a lot. I've replaced all the the 'mpiexe -n' with 'aprun -n' according to your advice. I first got error about environment variable 'OMPI_COMM_WORLD_RANK', to be specific, 
    def getnode(self):
        """Gets number of running task"""
       return int(os.environ['OMPI_COMM_WORLD_RANK'])
    I changed it to
      return int(os.environ['ALPS_APP_PE'])

Seems to run, but I got error as follows:

Copying data...
Starting iteration 1
Generating synthetics
Computing gradient
Traceback (most recent call last):
  File "/ufs/slurm/spool/daint02/job1761769/slurm_script", line 22, in <module>
    workflow.main()
  File "/users/hfang/packages/seisflows/seisflows/workflow/inversion.py", line 122, in main
    self.evaluate_gradient()
  File "/users/hfang/packages/seisflows/seisflows/workflow/inversion.py", line 237, in evaluate_gradient
    path=PATH.GRAD)
  File "/users/hfang/packages/seisflows/seisflows/postprocess/base.py", line 67, in write_gradient
    verbose=True))
  File "/users/hfang/packages/seisflows/seisflows/solver/base.py", line 244, in load
    keys, vals = loadbypar(path, self.parameters, iproc, prefix, suffix)
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 15, in loadbypar
    val = loadbin(path, iproc, prefix+key+suffix)
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 34, in loadbin
    return read_fortran(join(path, filename))
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 72, in read_fortran
    with open(filename, 'rb') as file:
IOError: [Errno 2] No such file or directory: u'/users/hfang/packages/tests/checkers/scratch/evalgrad/kernels/sum/proc000000_vs_kernel.bin'

Sometimes the code can run a few iterations without error, sometimes the code stops at the first iteration, seems randomly...

Still testing and will keep you updated.

**Comment by rmodrak** [comment]
Just to double check is this most recent traceback for NTASK==1 or NTASK>1?  

Also could you clarify have you tried using ``MPI.COMM_WORLD.Get_rank()`` together with the latest changes involving aprun?

The  OMPI_COMM_WORLD_RANK environment variable is specific to Open MPI, and was replaced a few weeks ago with a more general solution involving mpi4py.   Any advice I gave concerning OMPI_COMM_WORLD_RANK would have been before I realized the more general solution.

**Comment by HongjianFang** [comment]
The previous one was when NTASK=25, similar error came out as NTASK=1, as followed:

Starting iteration 2
Generating synthetics
Computing gradient
Traceback (most recent call last):
  File "/ufs/slurm/spool/daint04/job1761989/slurm_script", line 22, in <module>
    workflow.main()
  File "/users/hfang/packages/seisflows/seisflows/workflow/inversion.py", line 124, in main
    self.evaluate_gradient()
  File "/users/hfang/packages/seisflows/seisflows/workflow/inversion.py", line 239, in evaluate_gradient
    path=PATH.GRAD)
  File "/users/hfang/packages/seisflows/seisflows/postprocess/base.py", line 67, in write_gradient
    verbose=True))
  File "/users/hfang/packages/seisflows/seisflows/solver/base.py", line 244, in load
    keys, vals = loadbypar(path, self.parameters, iproc, prefix, suffix)
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 15, in loadbypar
    val = loadbin(path, iproc, prefix+key+suffix)
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 34, in loadbin
    return read_fortran(join(path, filename))
  File "/users/hfang/packages/seisflows/seisflows/seistools/io.py", line 63, in read_fortran
    with open(filename, 'rb') as file:
IOError: [Errno 2] No such file or directory: u'/users/hfang/packages/tests/checkers/scratch/evalgrad/kernels/sum/proc000000_vs_kernel.bin'

I've double checked, it uses  MPI.COMM_WORLD.Get_rank() in the getnode function.
I'll keep testing.

Cheers,
Fang

**Comment by rmodrak** [comment]
Hi Fang,

By chance, are you familiar with git commands and with how to fork a repository through github?  If so, then creating your own fork of seisflows and referring specific commits could be a more reliable to way troubleshoot.  If not, then it's perfectly alright, we should be able to continue in the current fashion.

One possibility is that we have fixed the issues related to seisflows.system, and we are now dealing with a different issue related to the SPECFEM2D xcombine_sem utility.

I heard recently of a possible bug in xcombine_sem that appears with certain cluster/compiler combinations.  Do you remember, which Fortran compiler did you specify with the SPECFEM2D configure command?

Best,
Ryan

**Comment by rmodrak** [comment]
Another possibility, which Matthieu Lefebvre pointed out, is that you may be exceeding the disk quota for your home directory midway through the inversion.  Because I would have expected an explicit error message, to me this seems less likely than, say, a bug in xcombine_sem.  Nevertheless, if you are not already doing so through a soft link or something like that, it might be good to work somewhere else other than your home directory.

**Comment by HongjianFang** [comment]
Hello Ryan,
    I just checked the config.log and found the compiler I used is icc and ifort. 
    BTW, I've changed to /scrach directory, which has a lot of disk space, but problem still remains.

Cheers,
Fang

**Comment by rmodrak** [comment]
Hi Fang, Thanks.  A bug in SPECFEM2D's xcombine_sem utility seems plausible.  Let me see look at it on my end.  

It might be faster if you could do one thing.  From the directory in which you submitted the inversion, could you attach the result of each of the following:  

```
ls -l ./scratch/evalgrad/*
ls -l ./scratch/solver/000000/
```

**Comment by rmodrak** [comment]
A possible fix would be to replace the file src/tomography/postprocess/combine_sem.f90 in SPECFEM2Dwith the version from the latest 

``` 
 use postprocess_par, only: MAX_STRING_LEN, MAX_KERNEL_PATHS, MAX_KERNEL_NAMES, &
    CUSTOM_REAL, NGLLX, NGLLZ, IIN, IOUT
```

**Comment by rmodrak** [comment]
Please disregard the last email notification. I hit enter by comment by accident.  Stay tuned for another update about a possible bug fix.

**Comment by rmodrak** [comment]
Hi Fang, to test whether xcombine_sem is to blame, you could try using the xcombine_sem executable compiled from the latest devel branch version of SPECFEM2D.  Make sure you replace only xcombine_sem, not any of the other executables.

**Comment by rmodrak** [comment]
Let me go ahead and close this issue--the system modules have changed a bit over the last year so the above discussion may no longer be relevant.
